# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on: 
    schedule:
        - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
    update-readme-with-blog: 
        name: Update blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://dev.to/feed/minecodes, https://minecodes.dd-dns.de/rss/"
